openapi: 3.0.0
info:
  version: '1.PreR15.1.0'
  title: '5G-EIR Equipment Identity Check'
  description: '5G-EIR Equipment Identity Check Service'
paths:
  /equipment-status:
    get:
      summary: Retrieves the status of the UE
      operationId: GetEquipmentStatus
      tags:
        - Equipment Status (Document)
      parameters:
        - name: pei
          in: query
          description: PEI of the UE
          required: true
          schema:
            $ref: '#/components/schemas/Pei' 
        - name: supi
          in: query
          description: SUPI of the UE
          required: false
          schema:
            $ref: '#/components/schemas/Supi' 
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EirResponseData'
        '404':
          description: PEI Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Unexpected error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    EirResponseData:
      type: object
      required:
        - status
      properties:
        status:
            $ref: '#/components/schemas/EquipmentStatus'
    Pei:
      type: string
      pattern: "([0-9]{14})"
    Supi:
      type: string
      pattern: "(imsi-[0-9]{5,15}|nai-.+)"
    EquipmentStatus:
      type: string
      enum:
        - WHITELISTED
        - BLACKLISTED
        - GREYLISTED
    ProblemDetails:
      description: 'https://www.rfc-editor.org/rfc/rfc7807.txt'
      type: object
      required:
        - type
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
externalDocs:
  description: Documentation
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.511/'
