openapi: 3.0.0
info:
  version: 1.PreR15.0.0
  title: 'Nudr_DataRepository API OpenAPI file'
  description: 'Unified Data Repository Service'
servers:
  - description: API root
    url: '{apiRoot}/nudr-dr/v1'
    variables:
      apiRoot:
        default: https://example.com
security:
  - oAuth2ClientCredentials: []
  - {}

paths:
  /subscription-data/{ueId}/authentication-data:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1authentication-data'
  /subscription-data/{ueId}/{servingPlmnId}/provisioned-data/am-data:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1%7BservingPlmnId%7D~1provisioned-data~1am-data'
  /subscription-data/{ueId}/{servingPlmnId}/provisioned-data/smf-selection-subscription-data:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1%7BservingPlmnId%7D~1provisioned-data~1smf-selection-subscription-data'
  /subscription-data/{ueId}/{servingPlmnId}/provisioned-data/sm-data:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1%7BservingPlmnId%7D~1provisioned-data~1sm-data'
  /subscription-data/{ueId}/context-data/amf-3gpp-access:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1amf-3gpp-access'
  /subscription-data/{ueId}/context-data/amf-non-3gpp-access:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1amf-non-3gpp-access'
  /subscription-data/{ueId}/context-data/smf-registrations:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1smf-registrations'
  /subscription-data/{ueId}/context-data/smf-registrations/{pduSessionId}:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1smf-registrations~1%7BpduSessionId%7D'
  /subscription-data/{ueId}/operator-specific-data:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1operator-specific-data'
  /subscription-data/{ueId}/context-data/smsf-3gpp-access:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1smsf-3gpp-access'
  /subscription-data/{ueId}/context-data/smsf-non-3gpp-access:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1smsf-non-3gpp-access'
  /subscription-data/{ueId}/{servingPlmnId}/provisioned-data/sms-mng-data:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1%7BservingPlmnId%7D~1provisioned-data~1sms-mng-data'
  /subscription-data/{ueId}/{servingPlmnId}/provisioned-data/sms-data:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1%7BservingPlmnId%7D~1provisioned-data~1sms-data'
  /subscription-data/{ueId}/pp-data:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1pp-data'
  /subscription-data/{ueId}/context-data/ee-subscriptions:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1ee-subscriptions'
  /subscription-data/{ueId}/context-data/ee-subscriptions/{subsId}:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1ee-subscriptions~1%7BsubsId%7D'
  /subscription-data/{ueId}/context-data/sdm-subscriptions:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1sdm-subscriptions'
  /subscription-data/{ueId}/context-data/sdm-subscriptions/{subsId}:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1sdm-subscriptions~1%7BsubsId%7D'
  /subscription-data/subs-to-notify:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1subs-to-notify'
  /subscription-data/subs-to-notify/{subsId}:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1subs-to-notify~1%7BsubsId%7D'
  /subscription-data/{ueId}/{servingPlmnId}/provisioned-data/trace-data:
    $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1%7BservingPlmnId%7D~1provisioned-data~1trace-data'
components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows: 
        clientCredentials: 
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes: {}
